### ISSUE TITLE
"timeout" ambiguous

### ISSUE THREAD

**Issue by jakearchibald** [inexorabletash/origin-flags#8]
When looking at the API it wasn't clear to me if timeout was a timeout for the flag request, or the operation once the flag was obtained (or both).

Rather than a specific timeout API, https://dom.spec.whatwg.org/#aborting-ongoing-activities might be more extensible. Eg, here's how to apply a 200ms timeout:

```js
async function get_lock_then_read() {
  const controller = new AbortController();
  const signal = controller.signal;

  setTimeout(() => controller.abort(), 200);

  const flag = await requestFlag('resource', 'shared', {signal});
  flag.waitUntil(async_read_func());
}
```

**Comment by inexorabletash** [comment]
The details say _"An optional timeout scan be specified in milliseconds. If the timeout passes before the flag request succeeds, the promise rejects with a TimeoutError. A timeout of 0 can be specified to attempt to acquire the flag but fail immediately if already held."_

But yeah, a more extensible form is probably good. Implementation-wise it would mean moving the responsibility for the timeout from the "coordinator" code to the "client" code, but I think that's fine.

So we'd have:
```webidl
dictionary FlagOptions {
  optional AbortSignal signal;
}
```
?

But I'm also curious about your thoughts on the top level question: timeouts on either the request or holding? Do both make sense? Good idea or bad idea?

With a signal on the requesting side and either explicit or promise-based release on the holding side, either can be done in user-space. With promise-based, I guess that's `waitUntil(Promise.race([completionPromise, abortPromise]))` ? (and you'd better not call waitUntil again)

**Comment by inexorabletash** [comment]
Aside: what's the status of `AbortController` in implementations/tests? It doesn't look like it's materialized in blink yet; I see tests WPT tests for fetch maybe?

**Comment by jakearchibald** [comment]
There are generic tests https://github.com/w3c/web-platform-tests/tree/eb84ee60e8bbbebb2b97dcdf192cbbf791c30f6c/dom/abort, and also fetch tests https://github.com/w3c/web-platform-tests/tree/0d311189506d0268f62198fde499a7a32fc58c87/fetch/api/abort.

Implementation hasn't started yet. https://bugs.chromium.org/p/chromium/issues/detail?id=750599.

However, this shouldn't block implementing other parts of this proposal.

**Comment by jakearchibald** [comment]
> So we'd have [code example]?

Yep!

> With a signal on the requesting side and either explicit or promise-based release on the holding side, either can be done in user-space

Good point. Is there any benefit to aborting the flag request, vs immediately releasing the flag once it's gained? If not, let's leave it to userland.

**Comment by inexorabletash** [comment]
>  Is there any benefit to aborting the flag request, vs immediately releasing the flag once it's gained?

Yes. A request can block subsequent requests, since they're intended to be processed in order. So aborting a request early will possibly let subsequent requests with overlapping scope be granted earlier.

**Comment by jakearchibald** [comment]
Ah of course, especially exclusive locks. Then yeah, I support aborting for the request. Aborting once you have the flag is easy in userland.

**Comment by inexorabletash** [comment]
Updated the README, speclet, IDL, and polyfill (but didn't polyfill the AbortSignal bit - PRs welcome!)

So... closing this (but re-open/file another bug if I missed something)
